name: Build Docker Image Template

on:
  workflow_call:
    inputs:
      repository_name:
        description: 'Repository name to release'
        required: true
        type: string
      version:
        description: 'Version to release'
        required: true
        type: string
      docker_context:
        description: 'Docker context to build'
        required: true
        type: string
      platforms:
        description: 'Platforms to build'
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        description: 'DockerHub username'
        required: true
      DOCKER_PASSWORD:
        description: 'DockerHub password'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.docker_context }}
          push: true
          tags: ${{ inputs.repository_name }}:${{ inputs.version }}
          platforms: ${{ inputs.platforms }}
          build-args: |
            TAG=${{ inputs.version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
