name: Jest

on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs: 
  unit-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: "14"
      - name: Setup
        working-directory: ./lib
        run: |
            npm install
            npm audit fix
            npm install --save-dev jest
      - name: SignIn Test
        working-directory: ./lib
        run: |
            npm test -- -u -t="SignIn"
      - name: SignOut Test
        working-directory: ./lib
        run: |
            npm test -- -u -t="SignOut"
      - name: isAuth Test
        working-directory: ./lib
        run: |
            npm test -- -u -t="isAuthenticated"
      - name: getBasicUserInfo Test
        working-directory: ./lib
        run: |
            npm test -- -u -t="getUserInfo"
      - name: refreshAccessToken Test
        working-directory: ./lib
        run: |
            npm test -- -u -t="refreshAccessToken"
      
    
