name: Tests

on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs: 
  unit-test:
    name: Tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: "14"
      - name: Setup
        working-directory: ./lib
        run: |
            npm install
            npm audit fix
            npm install --save-dev jest
            npm audit fix
            npm install --save-dev @testing-library/react 
            npm audit fix
            npm install --save-dev @testing-library/jest-dom
            npm audit fix
      - name: Test All
        working-directory: ./lib
        run: npm test
